name: CD (Deploy)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show branch
        run: echo "Deploying from branch $GITHUB_REF"

      - name: Simulate deployment
        run: echo "Deploying application..."